// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CREATE_DB_TABLE_SEED_USER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CREATE_DB_TABLE_SEED_USER));
        
        string IMigrationMetadata.Id
        {
            get { return "202211300320250_CREATE_DB_TABLE_SEED_USER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
