// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MAX_LENGTH_USERS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAX_LENGTH_USERS));
        
        string IMigrationMetadata.Id
        {
            get { return "202212061154343_MAX_LENGTH_USERS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
